Ft test
enoskyeza/lab-pro-management-system pull request #11
Opened 2022-06-25 09:25 UTC by enoskyeza

Features that were stated in the token are ready for review.

2022-06-25 10:47 UTC, Kyeza requested changes

2022-06-25 10:47 UTC, Kyeza commented on lab_management/admin.py
> +from . import models
change this import to
`from lab_management.models import Test `

2022-06-25 10:47 UTC, Kyeza commented on lab_management/admin.py
> +from cgi import test
remove this redundant code

2022-06-25 10:47 UTC, Kyeza commented on lap_pro/urls.py
>      path('patient/', include('patient_management.urls')),
rename these URLs to plural

- patients
- tests

2022-06-25 17:00 UTC, Kyeza requested changes

2022-06-25 17:00 UTC, Kyeza commented on lab_management/views.py
> +from .models import Test
Use absolute imports

2022-06-25 17:00 UTC, Kyeza commented on lab_management/views.py
> +from .forms import TestForm
Use absolute imports

2022-06-25 18:25 UTC, enoskyeza commented on lab_management/admin.py
> +from .models import Test
I had not understood what you meant, now that you say relative referencing I understand you well.

2022-06-25 18:52 UTC, enoskyeza commented on lab_management/admin.py
> +from .models import Test
but I have seen them using relative import in the django documentation more so when importing items from the same app.

2022-06-25 19:06 UTC, Kyeza commented on lab_management/admin.py
> +from .models import Test
Do what I have asked bro, it's better to use absolute

2022-06-26 20:03 UTC, Kyeza requested changes

2022-06-26 20:03 UTC, Kyeza commented on lab_management/models.py
> +    sample = models.ForeignKey(Sample, null=True, on_delete=models.SET_NULL)
add `blank=True` as it will allow this field to be left blank in order to be added later

2022-06-26 20:31 UTC, enoskyeza commented on lab_management/models.py
> +    lab_reference = models.CharField(max_length=150)
Alright

2022-06-27 10:35 UTC, Kyeza approved these changes

2022-06-27 10:35 UTC, merged